### ISSUE TITLE
setup.py install returns for for missing NEWS.txt

### ISSUE THREAD

**Issue by pc1oad1etter** [fscz/python-html-inliner#2]
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    NEWS = open(os.path.join(here, 'NEWS.txt')).read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/a/dev/python-webpage-inliner/NEWS.txt'

**Comment by fscz** [comment]
I think you are in the wrong place. There is no setup.py here.

**Comment by pc1oad1etter** [comment]
Wow, you are right.  python-webpage-inliner vs python-html-inliner. My bad.
